### ISSUE TITLE
Marcel::MimeType.for inconsistent results

### ISSUE THREAD

**Issue by ghost** [rails/marcel#4]
An issue was raised in Rails reporting ActiveStorage was not producing accurate MIME types. This is traced back to calling `Marcel::MimeType.for`:

https://github.com/rails/rails/blob/master/activestorage/app/models/active_storage/blob.rb
```ruby
  def extract_content_type(io)
      Marcel::MimeType.for io, name: filename.to_s, declared_type: content_type
    end
```

https://github.com/rails/rails/issues/32632

If the io starts with "Article" then it results in "message/news", otherwise 'text/csv'. Do you know what is happening here and how to fix it?

Please see examples below:
```ruby
2.5.0 Marcel::MimeType.for(StringIO.new("1895,1"), name: 'text.csv', declared_type: 'text/csv')
=> "text/csv"
2.5.0 Marcel::MimeType.for(StringIO.new("1895 1"), name: 'text.csv', declared_type: 'text/csv')
=> "text/csv"
2.5.0 Marcel::MimeType.for(StringIO.new("Article dates analysis"), name: 'text.csv', declared_type: 'text/csv')
=> "message/news"
2.5.0 Marcel::MimeType.for(StringIO.new("dates analysis"), name: 'text.csv', declared_type: 'text/csv')
=> "text/csv"
2.5.0 Marcel::MimeType.for(StringIO.new("Dates analysis"), name: 'text.csv', declared_type: 'text/csv')
=> "text/csv"
2.5.0 Marcel::MimeType.for(StringIO.new("article"), name: 'text.csv', declared_type: 'text/csv')
=> "text/csv"
2.5.0 Marcel::MimeType.for(StringIO.new("Article"), name: 'text.csv', declared_type: 'text/csv')
=> "message/news"
```

**Comment by ypresto** [comment]
This library is using latest (v0.3.2) versions of [mimemagic](https://github.com/minad/mimemagic) gem.
That gem uses the mime database provided by freedesktop.org (see http://freedesktop.org/wiki/Software/shared-mime-info/).
So this issue should be submitted to [shared-mime-info](https://freedesktop.org/wiki/Software/shared-mime-info/)'s own bug tracker instead of this gem.

**Comment by gmcgibbon** [comment]
This happens on the new Apache Tika DB as well. The magic rule is here: https://github.com/rails/marcel/blob/9f34b22608f74afb52df454e915f85cdb60e0a00/data/tika.xml#L6261-L6263

The funny thing is, this is a media type from 1993 that was marked as obsolete  in 2009 [by this RFC](https://datatracker.ietf.org/doc/html/rfc5537#section-4) according to the IANA: https://www.iana.org/assignments/media-types/message/news.

We may be able to propose this be removed upstream, or just remove obsolete types manually during table generation.

**Comment by gmcgibbon** [comment]
Opened https://issues.apache.org/jira/browse/TIKA-3421

**Comment by jeremy** [comment]
That is really bizarre! Once Tika is updated we can sync with Marcel. But yeah, out of scope otherwise.

What would be really helpful here is to allow Marcel to ignore certain magic-sniffed types, and provide a default list. Text matches like this one that are virtually 100% useless yet can lead to false positives should all be universally ignored.

Anyone interested in taking that on? Bonus would be generating such a list programmatically if there's any indication of obsolete types available in Tika.
